version: 0.2
phases:
  install:
    commands:
        - pip install awscli wheel setuptools pandas sagemaker
  pre_build:
    commands:
        - docker login --username ${DOCKER_HUB_USER} --password ${DOCKER_HUB_KEY} 
  build:
    commands:
       - bash build.sh ${CPU_FLAGS} -p ${DOCKER_HUB_REPO}
  post_build:
    commands:
       - bash push.sh ${CPU_FLAGS} -p ${DOCKER_HUB_REPO}